apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 500318249166.dkr.ecr.ap-south-1.amazonaws.com/dockerappdemo  # Replace with your ECR image URL
        ports:
        - containerPort: 3000  # Expose the port your React app is running on
